### PR TITLE
add support for detailed ACT DR6 noise models in monte carlo

### PR DESCRIPTION
**Pull request by xzackli**
This PR adds support for the ACT DR6 noise models in the [mnms](https://github.com/ACTCollaboration/mnms) package. Support for tiled and wavelet noise simulations requires specifying some additional noise parameters. I've added an example for just PA6 in the `paramfiles/global_dr6_v3_4pass_pa6.dict`. In this iteration, the param file for DR6 by default is essentially running the following (and then re-ordering the results for the pspipe scripts),
```python
from mnms import noise_models as nm

tnm = nm.TiledNoiseModel('pa6a', 'pa6b',  # or WaveletNoiseModel
    downgrade=4, lmax=5400, 
    notes='20211203', 
    mask_name="dr6v3_default_union_mask", 
    union_sources="20210209_sncut_10_aggressive")
map1 = tnm.get_sim(0, 123)  # split 0, sim 123
```
This setup, along with proper `.soapack.yml`, uses the pre-generated `20211203` models.

These noise simulations have a covariance model that is pre-generated on NERSC, but the new realizations are created on the fly. The random seed is set by the simulation spectrum index (specified by `iStart` and `iStop`), which must be in [0, 9999]. This specific implementation assumes that noise correlations are dominated by those between arrays on the same wafer, and thus generates noise simulations in pairs.

The notion of `pa6_f150` (pspipe array id) = `pa6b` (soapack qid) is implemented by hand in the param file.

### Todos before merge:
- [x] `.rst` file with a tutorial and a minimal soapack configuration for NERSC and tiger
- [x] testing to ensure the mean noise power spectra of the simulations matches the inputs

### CODE REVIEW

**Comment by xzackli** [comment]
@thibautlouis this PR is now tested, I fixed a remaining bug that caused issues with the signal spectrum. I've also written some documentation in the montecarlo folder, and added an example SLURM script.

I'm a little scared to merge however, as it turns out the changes are very close to where I rewrote large parts of the sim script. I will merge master with this PR by hand tomorrow and run some tests.

**Comment by xzackli** [comment]
@thibautlouis this is ready for merge! Feel free to merge when you have reviewed it.

**Comment by xzackli** [comment]
Much of the added complexity comes from having to include the pixel window. This is because the ACT DR6 mnms sims **do not** have a pixel window, which differs from the Gaussian realization. This was determined experimentally by comparing the sims to the Gaussian realizations from the script before.

**Comment by thibautlouis** [comment]
Hi Zack, thanks for this ! I'm a bit puzzled by how mnms handle pixel window function, in any case I don't think it should stop us for merging. if that's ok for you, for now we should keep the old version of mc_get_spectra.py in the pipeline and have this new version as another script maybe mc_mnms_get_spectra.py ? long term we will get rid of the former

**Comment by thibautlouis** [comment]
once it merge I will rename the data_analysis_utils function "deconvolve_pixwin_CAR", since it is a confusing name in this script and gave it a more general name

**Comment by xzackli** [comment]
@thibautlouis ok, I will commit a quick name change!

**Comment by xzackli** [comment]
Ok, now the new file is `mc_mnms_get_spectra.py` and I have restored the existing `mc_get_spectra.py`.

**Pull request merged**
